- do nice shutdown via web interface when shutting down. idea borrowed from gentoo
Changed files:
    mldonkey.init -> 1.18

diff --git a/mldonkey.init b/mldonkey.init
--- a/mldonkey.init
+++ b/mldonkey.init
@@ -33,25 +33,82 @@ if [ -f /etc/sysconfig/mldonkey ]; then
 	. /etc/sysconfig/mldonkey
 fi
 
+PROG=$(basename "$MLDONKEY_PATH")
+
+getpids() {
+	pgrep -u $USER $PROG
+}
+
+start() {
+	msg_starting mldonkey
+
+	daemon --fork --user $USER "cd ~$USER && exec $MLDONKEY_PATH > ${LOG:-/dev/null} 2>&1"
+	RETVAL=$?
+
+	if ! getpids > /dev/null; then
+		echo "MLDonkey could not be started! Check logfile: $LOG"
+		RETVAL=0
+	fi
+
+	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/mldonkey
+}
+
+stop() {
+	# first nicely, via web interface
+	BASE="http://"
+	if [[ -n ${USERNAME} && -n ${PASSWORD} ]]; then
+		BASE=${BASE}${USERNAME}:${PASSWORD}@
+	fi
+
+	msg_stopping mldonkey
+	BASE=${BASE}${SERVER}:${PORT}
+	wget -t 1 --spider ${BASE}/submit?q=close_fds -q
+	wget -t 1 --spider ${BASE}/submit?q=save -q
+	wget -t 1 --spider ${BASE}/submit?q=kill -q
+
+	if [ "$(getpids)" ]; then
+		fail
+		show "Waiting for MLDonkey to stop"
+		busy
+
+		RETVAL=0
+		timeout=0
+		while [ "$(getpids)" ]; do
+			if [ $timeout -ge 60 ]; then
+				RETVAL=1
+				break
+			fi
+
+			sleep 1
+			timeout=$((timeout + 1))
+		done
+	fi
+
+	# forcibly.
+	# killproc() sais itself ok or fail, therefore the if here
+	if [ "$(getpids)" ]; then
+		killproc $PROG
+		RETVAL=$?
+	else
+		[ $RETVAL -eq 0 ] && ok || fail
+	fi
+
+	rm -f /var/lock/subsys/mldonkey >/dev/null 2>&1
+
+}
+
 RETVAL=0
 case "$1" in
   start)
 	if [ ! -f /var/lock/subsys/mldonkey ]; then
-		msg_starting mldonkey
-		[ -z "$SERVICE_RUN_NICE_LEVEL" ] && SERVICE_RUN_NICE_LEVEL="+0"
-		daemon --user mldonkey "cd ~mldonkey && exec nice -n $SERVICE_RUN_NICE_LEVEL $MLDONKEY_PATH > /dev/null 2>&1 &"
-		RETVAL=$?
-		[ $RETVAL -eq 0 ] && touch /var/lock/subsys/mldonkey
+		start
 	else
 		msg_already_running mldonkey
 	fi
 	;;
   stop)
 	if [ -f /var/lock/subsys/mldonkey ]; then
-		msg_stopping mldonkey
-		killproc mlnetd
-		sleep 1
-		rm -f /var/lock/subsys/mldonkey >/dev/null 2>&1
+		stop
 	else
 		msg_not_running mldonkey
 	fi
@@ -66,7 +123,7 @@ case "$1" in
 	rm ~mldonkey/*.tmp >/dev/null 2>&1
 	;;
   status)
-	status mldonkey mlnetd
+	status mldonkey $PROG
 	exit $?
 	;;
   *)
